"""Does LibreOffice compute this template the way Excel does? (roadmap #13)

Generate's read-back results come from a LibreOffice recalculation, but
LibreOffice's IRR/XIRR root-finders, some financial functions and its
iterative-calculation settings differ from Excel's. This recalculates the
UNMODIFIED template in LibreOffice and compares every mapped output cell
with the value Excel last saved in the file: agreement means LibreOffice's
numbers for this template can stand in for Excel's; a difference is shown
per output. Read-only: the template file is never written.
"""

import math
import shutil
import tempfile
from pathlib import Path

import openpyxl

from app.services import excel_writer, mapping_service, recalc_service

REL_TOL = 1e-6
ABS_TOL = 1e-6


def _agrees(excel_value, lo_value) -> bool:
    if isinstance(excel_value, bool) or isinstance(lo_value, bool):
        return excel_value == lo_value
    if isinstance(excel_value, (int, float)) and isinstance(lo_value, (int, float)):
        return math.isclose(float(excel_value), float(lo_value), rel_tol=REL_TOL, abs_tol=ABS_TOL)
    return excel_value == lo_value


def check(template_path: Path, mappings: dict) -> dict:
    output_ids = [f["id"] for f in mapping_service.load_output_fields()]
    mapped = [fid for fid in output_ids if fid in mappings]
    if not mapped:
        return {"status": "noOutputsMapped", "rows": []}
    excel_values = excel_writer.read_output_values(template_path, mappings, mapped)
    if not excel_values:
        # Never saved by Excel (e.g. generated by a script): nothing to compare.
        return {"status": "noSavedValues", "rows": []}
    with tempfile.TemporaryDirectory() as tmp:
        copy = Path(tmp) / f"check{template_path.suffix}"
        shutil.copyfile(template_path, copy)
        # Prepare the copy exactly as Generate prepares its output (openpyxl
        # round-trip + full-calc-on-load): without the flag LibreOffice keeps
        # the cached values and the comparison would be vacuous.
        wb = openpyxl.load_workbook(copy, keep_vba=template_path.suffix.lower() == ".xlsm")
        wb.calculation.fullCalcOnLoad = True
        wb.save(copy)
        wb.close()
        recalc_service.recalc_with_libreoffice(copy)
        lo_values = excel_writer.read_output_values(copy, mappings, mapped)
    rows = []
    for fid in mapped:
        if fid not in excel_values:
            continue
        excel_value, lo_value = excel_values[fid], lo_values.get(fid)
        rows.append({
            "fieldId": fid,
            "excelValue": excel_value,
            "libreOfficeValue": lo_value,
            "agrees": _agrees(excel_value, lo_value),
        })
    status = "agrees" if all(r["agrees"] for r in rows) else "differs"
    return {"status": status, "rows": rows}
