// Chart kit — see README.md in this folder before adding a chart.
export { ChartFrame, DataTable } from './ChartFrame'
export type { ChartFrameProps } from './ChartFrame'
export { Legend } from './Legend'
export { Tooltip } from './Tooltip'
export { LineChart } from './LineChart'
export type { LineChartProps, LineSeries } from './LineChart'
export { BarChart } from './BarChart'
export type { BarChartProps, BarSeries } from './BarChart'
export { ScatterChart } from './ScatterChart'
export type { ScatterChartProps, ScatterPoint, ScatterSeries } from './ScatterChart'
export { StripPlot, DotPlot } from './StripPlot'
export type { StripPlotProps, StripRow, StripValue } from './StripPlot'
export { StatTile, StatTileRow } from './StatTile'
export type { StatDelta, StatTileProps } from './StatTile'
export { seriesColor, slotFor, VIZ } from './color'
export type { ChartTable, Formatter, LegendItem, ReferenceLine, SeriesSlot } from './types'
