// Roadmap #32: the Quick Screen napkin and the engine share test cases.
// This file is the source of the case inputs. It writes each case's napkin
// results and "Send to Deal Inputs" payload to a JSON file the backend reads
// (backend/tests/test_quick_screen_shared_cases.py), which runs the engine on
// the same payload and checks it lands near the napkin.
//
// After an intended change to the napkin math or the mapping, regenerate
// with `npx vitest run -u src/lib/quickScreenSharedCases.test.ts` and rerun
// the backend test.
import { expect, it } from 'vitest'
import {
  ACQUISITION_QUICK_SCREEN_DEFAULTS,
  QUICK_SCREEN_DEFAULTS,
  computeAcquisitionQuickScreen,
  computeQuickScreen,
  mapAcquisitionQuickScreenToDealInputs,
  mapQuickScreenToDealInputs,
  type AcquisitionQuickScreenInputs,
  type QuickScreenInputs,
} from './quickScreenMath'

const DEVELOPMENT_CASES: { name: string; inputs: QuickScreenInputs }[] = [
  { name: 'development defaults', inputs: QUICK_SCREEN_DEFAULTS },
  {
    name: 'development, long build at a high rate',
    inputs: { ...QUICK_SCREEN_DEFAULTS, constructionMonths: 30, constructionInterestRatePct: 0.095 },
  },
  {
    name: 'development, industrial by SF',
    inputs: {
      ...QUICK_SCREEN_DEFAULTS,
      sizeMode: 'sf',
      quantity: 200_000,
      landCost: 4_000_000,
      hardCostPerUnit: 110,
      rent: 12,
      noiMarginPct: 0.85,
      exitCapRatePct: 0.06,
    },
  },
  {
    name: 'development, all equity',
    inputs: { ...QUICK_SCREEN_DEFAULTS, ltcPct: 0 },
  },
]

const ACQUISITION_CASES: { name: string; inputs: AcquisitionQuickScreenInputs }[] = [
  { name: 'acquisition defaults', inputs: ACQUISITION_QUICK_SCREEN_DEFAULTS },
  {
    name: 'acquisition, interest-only',
    inputs: { ...ACQUISITION_QUICK_SCREEN_DEFAULTS, amortYears: 0 },
  },
  {
    name: 'acquisition, all cash',
    inputs: { ...ACQUISITION_QUICK_SCREEN_DEFAULTS, ltvPct: 0 },
  },
]

function sharedCases() {
  return {
    _comment:
      'Generated by frontend/src/lib/quickScreenSharedCases.test.ts (vitest -u). Do not edit by hand.',
    cases: [
      ...DEVELOPMENT_CASES.map(({ name, inputs }) => {
        const napkin = computeQuickScreen(inputs)
        return {
          name,
          kind: 'development',
          napkin: {
            totalCost: napkin.totalDevelopmentCost,
            stabilizedNoi: napkin.stabilizedNoi,
            yieldOnCost: napkin.yieldOnCost,
            loanAmount: napkin.loanAmount,
          },
          dealInputs: mapQuickScreenToDealInputs(inputs, napkin),
        }
      }),
      ...ACQUISITION_CASES.map(({ name, inputs }) => {
        const napkin = computeAcquisitionQuickScreen(inputs)
        return {
          name,
          kind: 'acquisition',
          napkin: {
            totalCost: napkin.totalBasis,
            stabilizedNoi: napkin.stabilizedNoi,
            goingInCapRate: napkin.goingInCapRate,
            loanAmount: napkin.loanAmount,
            annualDebtService: napkin.annualDebtService,
          },
          dealInputs: mapAcquisitionQuickScreenToDealInputs(inputs, napkin),
        }
      }),
    ],
  }
}

it('napkin results and deal-input payloads match the shared case file', async () => {
  await expect(`${JSON.stringify(sharedCases(), null, 2)}\n`).toMatchFileSnapshot(
    '../../../backend/tests/fixtures/quick_screen_cases.json',
  )
})
